import React, { useState } from 'react';
import Sidebar from './components/Sidebar';
import TopBar from './components/TopBar';
import TransactionListView from './components/TransactionListView';
import TransactionDetailView from './components/TransactionDetailView';
import { TransactionStatus, TransactionData, TransactionType } from './types';

// Helper to generate detail data based on selected row info
const getMockDetailData = (id: string, type: TransactionType, reference: string, date: string, status: TransactionStatus): TransactionData => {
  
  const baseData = {
    reference,
    creationDate: date,
    location: 'Kampala, Uganda',
    posId: '1FE12FC7410D2233',
    tokenId: '--',
    paymentMethod: 'Internal',
    serviceType: '--',
    status,
    remark: 'Generated by system',
    message: status === TransactionStatus.APPROVED ? '[000] Success' : '[102] Failed to process',
    type,
    commissions: {
      clientEarned: { currency: 'UGX', amount: 0 },
      veryPayEarned: { currency: 'UGX', amount: 0 },
      partnerEarned: { currency: 'UGX', amount: 0 },
    },
    ledger: []
  };

  // Specific logic for different types
  switch (type) {
    case 'Withdrawal':
      return {
        ...baseData,
        grossAmount: { currency: 'UGX', amount: 51000 },
        amount: { currency: 'UGX', amount: 50000 },
        paymentMethod: 'Bank Transfer',
        message: 'Withdrawal processed successfully',
        payer: {
          walletId: '25056523311111',
          amount: { currency: 'UGX', amount: 51000 },
          fee: { currency: 'UGX', amount: 1000 },
          fixedFee: { currency: 'UGX', amount: 1000 },
          percentageFee: '0%',
          total: { currency: 'UGX', amount: 51000 },
        },
        payee: {
          walletId: 'External Bank (Equity)',
          amount: { currency: 'UGX', amount: 50000 },
          fee: { currency: 'UGX', amount: 0 },
          fixedFee: { currency: 'UGX', amount: 0 },
          percentageFee: '0%',
          total: { currency: 'UGX', amount: 50000 },
        },
        ledger: [
          { id: '1', account: 'Wallet_111', accountType: 'Wallet', transactionType: 'Withdrawal', indicator: 'Debit', amount: { currency: 'UGX', amount: 51000 }, openingBalance: null, closingBalance: null, status: 'COMPLETED', dateTime: date },
          { id: '2', account: 'Settlement_Acc', accountType: 'Bank GL', transactionType: 'Settlement', indicator: 'Credit', amount: { currency: 'UGX', amount: 50000 }, openingBalance: null, closingBalance: null, status: 'COMPLETED', dateTime: date },
          { id: '3', account: 'Fee_Income', accountType: 'Revenue', transactionType: 'Fee', indicator: 'Credit', amount: { currency: 'UGX', amount: 1000 }, openingBalance: null, closingBalance: null, status: 'COMPLETED', dateTime: date },
        ]
      };
    
    case 'Funds in':
      return {
        ...baseData,
        grossAmount: { currency: 'UGX', amount: 24500 },
        amount: { currency: 'UGX', amount: 24500 },
        paymentMethod: 'Mobile Money',
        payer: {
          walletId: 'Ext Source (Airtel)',
          amount: { currency: 'UGX', amount: 24500 },
          fee: { currency: 'UGX', amount: 0 },
          fixedFee: { currency: 'UGX', amount: 0 },
          percentageFee: '0%',
          total: { currency: 'UGX', amount: 24500 },
        },
        payee: {
          walletId: '25056523322222',
          amount: { currency: 'UGX', amount: 24500 },
          fee: { currency: 'UGX', amount: 0 },
          fixedFee: { currency: 'UGX', amount: 0 },
          percentageFee: '0%',
          total: { currency: 'UGX', amount: 24500 },
        },
        ledger: [
           { id: '1', account: 'Trust_Bank_GL', accountType: 'Trust Account', transactionType: 'Deposit', indicator: 'Debit', amount: { currency: 'UGX', amount: 24500 }, openingBalance: null, closingBalance: null, status: 'COMPLETED', dateTime: date },
           { id: '2', account: 'Wallet_222', accountType: 'Wallet', transactionType: 'Deposit', indicator: 'Credit', amount: { currency: 'UGX', amount: 24500 }, openingBalance: null, closingBalance: null, status: 'COMPLETED', dateTime: date },
        ]
      };

    case 'Wallet Top Up':
        return {
          ...baseData,
          grossAmount: { currency: 'UGX', amount: 100000 },
          amount: { currency: 'UGX', amount: 100000 },
          paymentMethod: 'Card',
          payer: {
            walletId: 'Card ****4492',
            amount: { currency: 'UGX', amount: 100000 },
            fee: { currency: 'UGX', amount: 0 },
            fixedFee: { currency: 'UGX', amount: 0 },
            percentageFee: '0%',
            total: { currency: 'UGX', amount: 100000 },
          },
          payee: {
            walletId: '25056523389032',
            amount: { currency: 'UGX', amount: 100000 },
            fee: { currency: 'UGX', amount: 0 },
            fixedFee: { currency: 'UGX', amount: 0 },
            percentageFee: '0%',
            total: { currency: 'UGX', amount: 100000 },
          },
          ledger: [
            { id: '1', account: 'Acquiring_GL', accountType: 'Gateway', transactionType: 'Capture', indicator: 'Debit', amount: { currency: 'UGX', amount: 100000 }, openingBalance: null, closingBalance: null, status: 'COMPLETED', dateTime: date },
            { id: '2', account: 'Wallet_032', accountType: 'Wallet', transactionType: 'TopUp', indicator: 'Credit', amount: { currency: 'UGX', amount: 100000 }, openingBalance: null, closingBalance: null, status: 'COMPLETED', dateTime: date },
          ]
        };

    // Default to Payment logic (as per original mock)
    default:
      return {
        ...baseData,
        grossAmount: { currency: 'UGX', amount: 1000 },
        amount: { currency: 'UGX', amount: 990 },
        payer: {
          walletId: '25056523389032',
          amount: { currency: 'UGX', amount: 1000 },
          fee: { currency: 'UGX', amount: 30 },
          fixedFee: { currency: 'UGX', amount: 600 },
          percentageFee: '3%',
          total: { currency: 'UGX', amount: 1030 },
        },
        payee: {
          walletId: '25036572950124',
          amount: { currency: 'UGX', amount: 970 },
          fee: { currency: 'UGX', amount: 30 },
          fixedFee: { currency: 'UGX', amount: 0 },
          percentageFee: '3%',
          total: { currency: 'UGX', amount: 1000 },
        },
        commissions: {
          clientEarned: { currency: 'UGX', amount: 30 },
          veryPayEarned: { currency: 'UGX', amount: 30 },
          partnerEarned: { currency: 'UGX', amount: 0 },
        },
        ledger: [
          { id: '1', account: '26097123123', accountType: 'MSISDN', transactionType: 'Collection', indicator: 'Debit', amount: { currency: 'UGX', amount: 1000 }, openingBalance: null, closingBalance: null, status: 'COMPLETED', dateTime: date },
          { id: '2', account: '2560000000001', accountType: 'VeryPay OVA', transactionType: 'Collection', indicator: 'Credit', amount: { currency: 'UGX', amount: 900 }, openingBalance: null, closingBalance: null, status: 'COMPLETED', dateTime: date },
          { id: '3', account: '2600000000002', accountType: 'Provider Fee', transactionType: 'Collection', indicator: 'Credit', amount: { currency: 'UGX', amount: 100 }, openingBalance: null, closingBalance: null, status: 'COMPLETED', dateTime: date },
          { id: '4', account: '2560000000003', accountType: 'VeryPay OVA', transactionType: 'Disbursement', indicator: 'Debit', amount: { currency: 'UGX', amount: 900 }, openingBalance: { currency: 'UGX', amount: 1000000 }, closingBalance: { currency: 'UGX', amount: 999100 }, status: 'COMPLETED', dateTime: date },
          { id: '5', account: '26097123123000', accountType: 'Wallet', transactionType: 'Disbursement', indicator: 'Credit', amount: { currency: 'UGX', amount: 900 }, openingBalance: { currency: 'UGX', amount: 0 }, closingBalance: { currency: 'UGX', amount: 900 }, status: 'COMPLETED', dateTime: date }
        ]
      };
  }
};

const App: React.FC = () => {
  const [currentView, setCurrentView] = useState<'list' | 'detail'>('list');
  const [selectedTx, setSelectedTx] = useState<TransactionData | null>(null);

  const handleNavigate = (view: string) => {
    if (view === 'transactions') {
      setCurrentView('list');
      setSelectedTx(null);
    }
  };

  const handleRowClick = (id: string) => {
    // In a real app, we would find the item by ID from the list data
    // Here we will simulate finding it by mocking the list data access 
    // or just generating it based on the clicked row's known properties if we passed them.
    // For this demo, I need to know which type was clicked. 
    // I'll grab the raw list item from a local constant in TransactionListView (conceptually)
    // To make it simple, let's look up from a shared mock source or just pass the type.
    
    // Quick Hack: Find the item in the mock data defined in the view (conceptually lifted here)
    const mockList = [
      { id: '1', type: 'Payment', ref: 'FG08L358AC5', date: '11/21/2025 11:08:18', status: TransactionStatus.APPROVED },
      { id: '2', type: 'Withdrawal', ref: 'WA92M192XX9', date: '11/21/2025 10:45:12', status: TransactionStatus.APPROVED },
      { id: '3', type: 'Funds in', ref: 'FU11K291YY1', date: '11/21/2025 09:30:00', status: TransactionStatus.FAILED },
      { id: '4', type: 'Wallet Top Up', ref: 'WT88J102ZZ3', date: '11/20/2025 18:15:33', status: TransactionStatus.APPROVED },
      { id: '5', type: 'Pre-funded', ref: 'PF77H111AA4', date: '11/20/2025 14:20:10', status: TransactionStatus.PENDING },
      { id: '6', type: 'Deactivation Transfer', ref: 'DT55G222BB5', date: '11/20/2025 12:00:00', status: TransactionStatus.APPROVED },
      { id: '7', type: 'Funds out', ref: 'FO99F333CC6', date: '11/19/2025 16:45:22', status: TransactionStatus.DECLINED },
      { id: '8', type: 'Payment', ref: 'PA11E444DD7', date: '11/19/2025 09:10:05', status: TransactionStatus.APPROVED },
      { id: '9', type: 'Withdrawal', ref: 'WA22D555EE8', date: '11/18/2025 21:30:00', status: TransactionStatus.APPROVED },
      { id: '10', type: 'Wallet Top Up', ref: 'WT33C666FF9', date: '11/18/2025 19:15:15', status: TransactionStatus.APPROVED },
    ];

    const item = mockList.find(i => i.id === id);
    if (item) {
      const detailData = getMockDetailData(id, item.type as TransactionType, item.ref, item.date, item.status);
      setSelectedTx(detailData);
      setCurrentView('detail');
    }
  };

  const handleBack = () => {
    setCurrentView('list');
    setSelectedTx(null);
  };

  return (
    <div className="min-h-screen bg-[#f3f4f6] font-sans text-slate-900">
      <TopBar />
      <Sidebar onNavigate={handleNavigate} />
      
      {/* Main Content Wrapper */}
      <div className="pt-14 lg:pl-64 transition-all duration-300 h-screen overflow-hidden">
        {currentView === 'list' ? (
          <TransactionListView onRowClick={handleRowClick} />
        ) : (
          <div className="h-full overflow-y-auto">
             {selectedTx && <TransactionDetailView data={selectedTx} onBack={handleBack} />}
          </div>
        )}
      </div>
    </div>
  );
};

export default App;